### PR TITLE
#48 - Flush writer pipe; don't close it.

### LINKED ISSUE #48: Race condition when `close`ing the Pipe() used for redirect_*
There is a race condition in the implementation of the capture_* and suppress_* macros, described in this julia issue: https://github.com/JuliaLang/julia/issues/47759#issuecomment-1334194540, racing against another Task in another Thread doing logging.

It comes from the fact that we do not lock around the critical section in between "redirect" and "close":
https://github.com/JuliaIO/Suppressor.jl/blob/cbfc46f1450b03d6b69dad4c35de739290ff0aff/src/Suppressor.jl#L65-L72

If another task starts a log message and grabs a local reference to `stderr` before the redirect, it will grab a local reference to the Pipe. And then if it finishes logging after the Pipe has been closed, the log message will throw an error.

You can see this easily with this program:
```julia
Threads.nthreads()  # 4

using Suppressor

t = Threads.@spawn begin
    for _ in 1:100
        @info "hello, friends"
        sleep(0.001)
    end
end

for _ in 1:1000
    @suppress_err sleep(0.001)
end

display(t)
```
Which for me gives:
```
Task (failed) @0x000000011353af50
IOError: stream is closed or unusable
```

---------------------

We think the easiest fix would be to _not manually close the Pipe_, but rather to let GC close it, once all references have disappeared. This ensures that if someone has accidentally grabbed a reference to stderr in another thread, that they will not break because the Pipe is closed.

I'm not sure whether GC will already close a pipe when it's GC'd, or if we would need to add a finalizer for it? But either way, I think that's probably the best solution.

CC: @vilterp, @dewilson.

### PR DESCRIPTION
**Pull request by NHDaly**
Fixes #48: Flush writer pipe; don't close it.

Since closing the pipe can cause race conditions with someone writing to the pipe, it's better to flush it, and then leave closing the pipe endpoint to GC.

### CODE REVIEW

File: src/Suppressor.jl [hunk 1]
```diff
@@ -36,7 +36,7 @@ macro suppress(block)
         finally
             if ccall(:jl_generating_output, Cint, ()) == 0
                 redirect_stdout(original_stdout)
-                close(out_wr)
+                flush(out_wr)
```
Comment (NHDaly) [inline src/Suppressor.jl:40]: My main open question here is:
- Does GC close a PipeEndpoint when it is GC'd? Or do we need to manually add a Finalizer to do this?

**Comment by NHDaly** [comment]
CC: @dewilson, @vilterp

File: src/Suppressor.jl (hunk 1 above)
Comment (NHDaly) [reply src/Suppressor.jl:40]: The answer is yes it does.

File: src/Suppressor.jl [hunk 2]
```diff
@@ -110,6 +110,21 @@ macro suppress_err(block)
...
+        # Swallow this exception so the task fails gracefully.
+        # HACK:
+        # Now, create a new sticky task to force the Thread to forget about
+        # this task, which would otherwise keep the IOs alive, since they're
+        # captured in the lambda this task was created with.
+        # (This should really be fixed in the scheduler. See:
+        # https://github.com/JuliaLang/julia/issues/40626)
+        @async nothing
+    end
+end
```
Comment (NHDaly) [inline src/Suppressor.jl:126]: 😕 okay SO: this _does_ fix the tests, and this is now a working solution.

HOWEVER: It made me realize one other caveat with this approach.
Before, a task could _throw an exception_ if it attempted to log from one thread while another thread is doing `@capture_err`.
NOW: it's possible for its log message to be SILENTLY DROPPED during that race condition, which is maybe just as bad?

So maybe the real answer is actually to fix https://github.com/JuliaLang/julia/issues/47759 on the logger side, and leave this package alone? :/

It's sad because this fix seemed easier, but maybe less so now after these changes.

File: src/Suppressor.jl [hunk 3]
```diff
@@ -121,20 +136,24 @@ macro capture_out(block)
...
-                close(out_wr)
+                flush(out_wr)
             end
         end
 
         if ccall(:jl_generating_output, Cint, ()) == 0
-            fetch(out_reader)
+            s = String(take!(io_buf))
+            # Now close the task to allow the Pipe() to be GC'd
+            close(io_buf)
```
Comment (Drvi) [inline src/Suppressor.jl:155]: I _think_ at this point you need write something to the pipe and flush to make sure the task dies.
